language: python
services:
        - docker
before_install:
        - sudo docker build -t csec380-proj server
        - sudo docker run -dit --name csec380-proj -p 8080:8080 csec380-proj
        - pip install -r  tests/requirements.txt
script:
        - pytest
