version: '3'
services: 
        apache2-1:
                build: ./
                volumes:
                        - ./src/:/var/www/html/
                ports:
                        - 8080:8080

