version: '3'
services: 
    db:
        container_name: flask_db
        build: ./Database
        restart: always
        networks:
            - back
    app:
        container_name: flask_app
        build: ./Application
        depends_on:
            - db
        networks:
            - back
    proxy:
        build: ./Proxy
        ports:
            - 443:443
        depends_on:
            - db
            - app
        networks:
            - front
            - back
networks:
    front:
    back:
