version: '3'
services: 
    db:
        build: ./Database
        restart: always
        environment:
            #we're security majors, not secure majors.  Changeme.
            MYSQL_ROOT_PASSWORD: absolutely_totally_secure
    app:
        build: ./Application
        ports: 
            - 5001:5001
        links:
            - db
        depends_on:
            - db