# app may throw an error. Do not be alarmed. App is still up.
version: '3'
services: 
    db:
        build: ./Database
        restart: always
        environment:
            #we're security majors, not secure majors.  Changeme.
            MYSQL_ROOT_PASSWORD: absolutely_totally_secure
        ports:
            - 3306:3306
    app:
        build: ./Application
        restart: on-failure:5
        ports: 
            - 5000:5000
        links:
            - db
        depends_on:
            - db
    proxy:
        build: ./Proxy
        restart: on-failure:5
        ports:
            - 443:443
        links:
            - app
        depends_on:
            - app